# -*- coding: utf-8 -*-
"""Image Classifier Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f6MTNJktMgcFBS5yQUHWQcDIiAGjIXij

## Prepare the workspace
"""

# Code to read csv file into colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)



# Before you proceed, update the PATH
import os
os.environ['PATH'] = f"{os.environ['PATH']}:/root/.local/bin"
os.environ['PATH'] = f"{os.environ['PATH']}:/opt/conda/lib/python3.6/site-packages"
# Restart the Kernel at this point.

# Do not execute the commands below unless you have restart the Kernel after updating the PATH.
#!python -m pip install torch==1.0.0

# Check torch version and CUDA status if GPU is enabled.
import torch
print(torch.__version__)
print(torch.cuda.is_available()) # Should return True when GPU is enabled.

"""# Developing an AI application

Going forward, AI algorithms will be incorporated into more and more everyday applications. For example, you might want to include an image classifier in a smart phone app. To do this, you'd use a deep learning model trained on hundreds of thousands of images as part of the overall application architecture. A large part of software development in the future will be using these types of models as common parts of applications.

In this project, you'll train an image classifier to recognize different species of flowers. You can imagine using something like this in a phone app that tells you the name of the flower your camera is looking at. In practice you'd train this classifier, then export it for use in your application. We'll be using [this dataset](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html) of 102 flower categories, you can see a few examples below.

<img src='assets/Flowers.png' width=500px>

The project is broken down into multiple steps:

* Load and preprocess the image dataset
* Train the image classifier on your dataset
* Use the trained classifier to predict image content

We'll lead you through each part which you'll implement in Python.

When you've completed this project, you'll have an application that can be trained on any set of labeled images. Here your network will be learning about flowers and end up as a command line application. But, what you do with your new skills depends on your imagination and effort in building a dataset. For example, imagine an app where you take a picture of a car, it tells you what the make and model is, then looks up information about it. Go build your own dataset and make something new.

First up is importing the packages you'll need. It's good practice to keep all the imports at the beginning of your code. As you work through this notebook and find you need to import a package, make sure to add the import up here.
"""

# Commented out IPython magic to ensure Python compatibility.
# Imports here
# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'

import matplotlib.pyplot as plt

import torch
from torchvision import datasets, transforms, models
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
import json
from PIL import Image
import numpy as np
import seaborn as sns
from torchvision.models import vgg16
import torch.nn.functional as F

"""## Load the data

Here you'll use `torchvision` to load the data ([documentation](http://pytorch.org/docs/0.3.0/torchvision/index.html)). The data should be included alongside this notebook, otherwise you can [download it here](https://s3.amazonaws.com/content.udacity-data.com/nd089/flower_data.tar.gz).
"""

from google.colab import drive
drive.mount('/content/drive')

"/content/drive"

import os

"""If you do not find the `flowers/` dataset in the current directory, **/workspace/home/aipnd-project/**, you can download it using the following commands.

```bash
!wget 'https://s3.amazonaws.com/content.udacity-data.com/nd089/flower_data.tar.gz'
!unlink flowers
!mkdir flowers && tar -xzf flower_data.tar.gz -C flowers
```

## Data Description
The dataset is split into three parts, training, validation, and testing. For the training, you'll want to apply transformations such as random scaling, cropping, and flipping. This will help the network generalize leading to better performance. You'll also need to make sure the input data is resized to 224x224 pixels as required by the pre-trained networks.

The validation and testing sets are used to measure the model's performance on data it hasn't seen yet. For this you don't want any scaling or rotation transformations, but you'll need to resize then crop the images to the appropriate size.

The pre-trained networks you'll use were trained on the ImageNet dataset where each color channel was normalized separately. For all three sets you'll need to normalize the means and standard deviations of the images to what the network expects. For the means, it's `[0.485, 0.456, 0.406]` and for the standard deviations `[0.229, 0.224, 0.225]`, calculated from the ImageNet images.  These values will shift each color channel to be centered at 0 and range from -1 to 1.
"""

data_dir = '/content/drive/MyDrive/flower_data'
train_dir = os.path.join(data_dir, 'train')
valid_dir = os.path.join(data_dir, 'valid')
test_dir = os.path.join(data_dir, 'test')

# TODO: Define your transforms for the training, validation, and testing sets
train_transforms=  transforms.Compose([
        transforms.RandomRotation(30),
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
valid_transforms =  transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
test_transforms =  transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])


# TODO: Load the datasets with ImageFolder
train_data = datasets.ImageFolder(train_dir, transform=train_transforms)
valid_data = datasets.ImageFolder(valid_dir , transform=valid_transforms)
test_data = datasets.ImageFolder(test_dir, transform=test_transforms)

# TODO: Using the image datasets and the trainforms, define the dataloaders
trainloader = torch.utils.data.DataLoader(train_data, batch_size=64, shuffle=True)
validloader = torch.utils.data.DataLoader(valid_data, batch_size=64)
testloader = torch.utils.data.DataLoader(test_data, batch_size=64)



model = models.densenet121(pretrained = True)
model



"""### Label mapping

You'll also need to load in a mapping from category label to category name. You can find this in the file `cat_to_name.json`. It's a JSON object which you can read in with the [`json` module](https://docs.python.org/2/library/json.html). This will give you a dictionary mapping the integer encoded categories to the actual names of the flowers.
"""

import json

file_path = '/content/drive/MyDrive/cat_to_name.json'

with open(file_path, 'r') as f:
    cat_to_name = json.load(f)

cat_to_name

"""# Building and training the classifier

Now that the data is ready, it's time to build and train the classifier. As usual, you should use one of the pretrained models from `torchvision.models` to get the image features. Build and train a new feed-forward classifier using those features.

We're going to leave this part up to you. Refer to [the rubric](https://review.udacity.com/#!/rubrics/1663/view) for guidance on successfully completing this section. Things you'll need to do:

* Load a [pre-trained network](http://pytorch.org/docs/master/torchvision/models.html) (If you need a starting point, the VGG networks work great and are straightforward to use)
* Define a new, untrained feed-forward network as a classifier, using ReLU activations and dropout
* Train the classifier layers using backpropagation using the pre-trained network to get the features
* Track the loss and accuracy on the validation set to determine the best hyperparameters

We've left a cell open for you below, but use as many as you need. Our advice is to break the problem up into smaller parts you can run separately. Check that each part is doing what you expect, then move on to the next. You'll likely find that as you work through each part, you'll need to go back and modify your previous code. This is totally normal!

When training make sure you're updating only the weights of the feed-forward network. You should be able to get the validation accuracy above 70% if you build everything right. Make sure to try different hyperparameters (learning rate, units in the classifier, epochs, etc) to find the best model. Save those hyperparameters to use as default values in the next part of the project.

One last important tip if you're using the workspace to run your code: To avoid having your workspace disconnect during the long-running tasks in this notebook, please read in the earlier page in this lesson called Intro to
GPU Workspaces about Keeping Your Session Active. You'll want to include code from the workspace_utils.py module.

## Note for Workspace users:
If your network is over 1 GB when saved as a checkpoint, there might be issues with saving backups in your workspace. Typically this happens with wide dense layers after the convolutional layers. If your saved checkpoint is larger than 1 GB (you can open a terminal and check with `ls -lh`), you should reduce the size of your hidden layers and train again.
"""



# Use GPU if it's available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.densenet121(pretrained=True)
#model = models.vgg16(pretrained=True)


# Freeze parameters so we don't backprop through them
for param in model.parameters():
    param.requires_grad = False

# Define a new, untrained feed-forward network as a classifier
classifier = nn.Sequential(
    nn.Linear(1024, 4096),
    nn.ReLU(inplace = True),
    nn.Dropout(p=0.5),
    nn.Linear(4096, 102),
    nn.LogSoftmax(dim=1)
)

model.classifier = classifier
criterion = nn.NLLLoss()
#only train the classifier params, feature params are frozen.
optimizer = optim.Adam(model.classifier.parameters(), lr=0.002)

model.to(device);



# Build and train your network
num_epochs = 5
for epoch in range(1, num_epochs + 1):
   batch_counter = 0
   training_loss = 0


   for images , labels in trainloader:


       images, labels = images.to(device), labels.to(device)
       batch_counter += 1
       optimizer.zero_grad()
       prediction = model(images)
       loss = criterion(prediction, labels)
       loss.backward()
       optimizer.step()
       training_loss += loss.item()


       #to show traininng loss after some batches of epochs
       if batch_counter % 30 == 0:
           model.eval()
           testing_accuracy = 0
           testing_loss = 0
           with torch.no_grad():
             for images_test, labels_test in validloader:
               images_test, labels_test = images_test.to(device), labels_test.to(device)




               images_test, labels_test = images_test.to(device), labels_test.to(device)


               testing_loss += criterion(prediction, labels)
               prediction_exp_prob_test = torch.exp(prediction)
               actual_highest_value_test, index_of_highest_values_test = prediction_exp_prob_test.topk(1)


               # Ensure labels_test has the same batch size as index_of_highest_values_test
               if index_of_highest_values_test.size(0) != labels_test.size(0):

                 min_batch_size = min(index_of_highest_values_test.size(0), labels_test.size(0))
                 index_of_highest_values_test = index_of_highest_values_test[:min_batch_size]
                 labels_test = labels_test[:min_batch_size].view(-1, 1)


               comparison_test = (index_of_highest_values_test == labels_test).sum().item()
               testing_accuracy += comparison_test
           # print
           print(f"Epoch: {epoch} | Batch: {batch_counter} | Training loss: {round(training_loss, 2)} | Validation loss: {round((testing_loss/len(validloader)).item(), 2)} | Validation Accuracy: {round(testing_accuracy/len(validloader.dataset)*100, 2)}")
           print("----------------------------------------")
           # setting training loss to zero because we want to see the loss for next 30 batches and it should be decreasing if model is learning well (as it will make better and better predictions so loss will be smaller and smaller)
           training_loss = 0

"""## Testing your network

It's good practice to test your trained network on test data, images the network has never seen either in training or validation. This will give you a good estimate for the model's performance on completely new images. Run the test images through the network and measure the accuracy, the same way you did validation. You should be able to reach around 70% accuracy on the test set if the model has been trained well.
"""

# TODO: Do validation on the test set
#We set the model to evaluation mode using model.eval(). This is important because
#it disables dropout and batch normalization layers which behave differently
#during training and inference.
correct = 0
total = 0
model.eval()

#We iterate through the test dataloader and forward pass the test images through the model.
with torch.no_grad():
    for inputs, labels in testloader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = correct / total
print(f"Test Accuracy: {test_accuracy*100:.2f}%")

"""## Save the checkpoint

Now that your network is trained, save the model so you can load it later for making predictions. You probably want to save other things such as the mapping of classes to indices which you get from one of the image datasets: `image_datasets['train'].class_to_idx`. You can attach this to the model as an attribute which makes inference easier later on.

```model.class_to_idx = image_datasets['train'].class_to_idx```

Remember that you'll want to completely rebuild the model later so you can use it for inference. Make sure to include any information you need in the checkpoint. If you want to load the model and keep training, you'll want to save the number of epochs as well as the optimizer state, `optimizer.state_dict`. You'll likely want to use this trained model in the next part of the project, so best to save it now.
"""

# TODO: Save the checkpoint
# Define checkpoint dictionary
checkpoint = {
    'model': model,
    'class_to_idx': train_data.class_to_idx,
    'state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'num_epochs': num_epochs
}

# Save the checkpoint to a file
torch.save(checkpoint, 'checkpoint.pth')



"""## Loading the checkpoint

At this point it's good to write a function that can load a checkpoint and rebuild the model. That way you can come back to this project and keep working on it without having to retrain the network.
"""

# TODO: Write a function that loads a checkpoint and rebuilds the model
def load_checkpoint(filepath):
    # Load the checkpoint
    checkpoint = torch.load(filepath)

    # Rebuild the model architecture
    model = checkpoint['model']
    model.classifier = nn.Sequential(
        nn.Linear(25088, 4096),
        nn.ReLU(),
        nn.Dropout(0.5),
        nn.Linear(4096, len(checkpoint['class_to_idx'])),
        nn.LogSoftmax(dim=1)
    )
    model.load_state_dict(checkpoint['state_dict'])

    # Attach class_to_idx to the model
    model.class_to_idx = checkpoint['class_to_idx']

    return model

"""# Inference for classification

Now you'll write a function to use a trained network for inference. That is, you'll pass an image into the network and predict the class of the flower in the image. Write a function called `predict` that takes an image and a model, then returns the top $K$ most likely classes along with the probabilities. It should look like

```python
probs, classes = predict(image_path, model)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```

First you'll need to handle processing the input image such that it can be used in your network.

## Image Preprocessing

You'll want to use `PIL` to load the image ([documentation](https://pillow.readthedocs.io/en/latest/reference/Image.html)). It's best to write a function that preprocesses the image so it can be used as input for the model. This function should process the images in the same manner used for training.

First, resize the images where the shortest side is 256 pixels, keeping the aspect ratio. This can be done with the [`thumbnail`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.thumbnail) or [`resize`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.thumbnail) methods. Then you'll need to crop out the center 224x224 portion of the image.

Color channels of images are typically encoded as integers 0-255, but the model expected floats 0-1. You'll need to convert the values. It's easiest with a Numpy array, which you can get from a PIL image like so `np_image = np.array(pil_image)`.

As before, the network expects the images to be normalized in a specific way. For the means, it's `[0.485, 0.456, 0.406]` and for the standard deviations `[0.229, 0.224, 0.225]`. You'll want to subtract the means from each color channel, then divide by the standard deviation.

And finally, PyTorch expects the color channel to be the first dimension but it's the third dimension in the PIL image and Numpy array. You can reorder dimensions using [`ndarray.transpose`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.transpose.html). The color channel needs to be first and retain the order of the other two dimensions.
"""

def process_image(image):
    ''' Scales, crops, and normalizes a PIL image for a PyTorch model,
        returns an Numpy array
    '''

    # TODO: Process a PIL image for use in a PyTorch model

    # Define transformations for the input image
    preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # Open the image using PIL
    img = Image.open(image)

    # Apply transformations
    img = preprocess(img)

    # Convert the image to a numpy array
    img = np.array(img)

    return img

"""To check your work, the function below converts a PyTorch tensor and displays it in the notebook. If your `process_image` function works, running the output through this function should return the original image (except for the cropped out portions)."""

def imshow(image, ax=None, title=None):
    """Imshow for Tensor."""
    if ax is None:
        fig, ax = plt.subplots()

    # PyTorch tensors assume the color channel is the first dimension
    # but matplotlib assumes is the third dimension
    image = image.numpy().transpose((1, 2, 0))

    # Undo preprocessing
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    image = std * image + mean

    # Image needs to be clipped between 0 and 1 or it looks like noise when displayed
    image = np.clip(image, 0, 1)

    ax.imshow(image)

    return ax

"""## Class Prediction

Once you can get images in the correct format, it's time to write a function for making predictions with your model. A common practice is to predict the top 5 or so (usually called top-$K$) most probable classes. You'll want to calculate the class probabilities then find the $K$ largest values.

To get the top $K$ largest values in a tensor use [`x.topk(k)`](http://pytorch.org/docs/master/torch.html#torch.topk). This method returns both the highest `k` probabilities and the indices of those probabilities corresponding to the classes. You need to convert from these indices to the actual class labels using `class_to_idx` which hopefully you added to the model or from an `ImageFolder` you used to load the data ([see here](#Save-the-checkpoint)). Make sure to invert the dictionary so you get a mapping from index to class as well.

Again, this method should take a path to an image and a model checkpoint, then return the probabilities and classes.

```python
probs, classes = predict(image_path, model)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```
"""

def predict(image_path, model, topk=5):
    ''' Predict the class (or classes) of an image using a trained deep learning model.
    '''

    # Load and process the image
    img = process_image(image_path)

    # Convert numpy array to torch tensor
    img = torch.from_numpy(img).unsqueeze(0)

    # Move tensor to device
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    img = img.to(device)

    # Set the model to evaluation mode
    model.eval()

    # Disable gradient calculation
    with torch.no_grad():
        # Forward pass
        output = model(img)

        # Get topk probabilities and classes
        probabilities, classes = torch.topk(output, topk)

        # Convert probabilities and classes to numpy arrays
        probabilities = probabilities.exp().cpu().numpy()[0]
        classes = classes.cpu().numpy()[0]

        return probabilities, classes

import numpy as np
import matplotlib.pyplot as plt

def imshow(image, ax=None, title=None):
    """Imshow for Tensor."""
    if ax is None:
        fig, ax = plt.subplots()

    # PyTorch tensors assume the color channel is the first dimension
    # but matplotlib assumes is the third dimension
    if isinstance(image, torch.Tensor):
        image = image.cpu().numpy().transpose((1, 2, 0))
    else:
        image = image.transpose((1, 2, 0))

    # Undo preprocessing
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    image = std * image + mean

    # Image needs to be clipped between 0 and 1 or it looks like noise when displayed
    image = np.clip(image, 0, 1)

    ax.imshow(image)
    ax.axis('off')
    if title:
        ax.set_title(title)

    return ax

"""## Sanity Checking

Now that you can use a trained model for predictions, check to make sure it makes sense. Even if the testing accuracy is high, it's always good to check that there aren't obvious bugs. Use `matplotlib` to plot the probabilities for the top 5 classes as a bar graph, along with the input image. It should look like this:

<img src='assets/inference_example.png' width=300px>

You can convert from the class integer encoding to actual flower names with the `cat_to_name.json` file (should have been loaded earlier in the notebook). To show a PyTorch tensor as an image, use the `imshow` function defined above.
"""



imshow(process_image("/content/WhatsApp Image 2024-02-22 at 16.29.26.jpeg"))

image_path = "/content/WhatsApp Image 2024-02-22 at 16.29.26.jpeg"

# Call the predict function with the model and image file path
probabilities, classes = predict(image_path, model)

# Print the top 5 predicted classes and their probabilities
for i in range(len(probabilities)):
    print(f"Class: {classes[i]}, Probability: {probabilities[i]}")

for i in classes:
    print(f"{i.item()}: {cat_to_name[str(i.item())]}")

def plot_solution(image_path, model):
    # Call predict function to get top 5 probabilities and classes
    probabilities, classes = predict(image_path, model, topk=5)

    # Convert class indices to flower names using cat_to_name dictionary
    class_names = [cat_to_name[str(cls)] for cls in classes]

    # Load and process the input image
    img = process_image(image_path)

    # Plot input image
    plt.figure(figsize=(6, 10))
    ax = plt.subplot(2, 1, 1)
    imshow(img, ax)
    ax.axis('off')

    # Plot bar graph for top 5 classes
    plt.subplot(2, 1, 2)
    plt.barh(range(5), probabilities, align='center')
    plt.yticks(range(5), class_names)
    plt.gca().invert_yaxis()  # Invert y-axis to show highest probability at the top
    plt.xlabel('Probability')
    plt.title('Top 5 Predictions')
    plt.show()

# Call plot_solution function with the image path and the trained model
plot_solution(image_path, model)

image_path1 = "/content/WhatsApp Image 2024-02-22 at 16.31.31.jpeg"

# Call the predict function with the model and image file path
probabilities, classes = predict(image_path, model)

# Print the top 5 predicted classes and their probabilities
for i in range(len(probabilities)):
    print(f"Class: {classes[i]}, Probability: {probabilities[i]}")

def plot_solution(image_path, model):
    # Call predict function to get top 5 probabilities and classes
    probabilities, classes = predict(image_path1, model, topk=5)

    # Convert class indices to flower names using cat_to_name dictionary
    class_names = [cat_to_name[str(cls)] for cls in classes]

    # Load and process the input image
    img = process_image(image_path1)

    # Plot input image
    plt.figure(figsize=(6, 10))
    ax = plt.subplot(2, 1, 1)
    imshow(img, ax)
    ax.axis('off')

    # Plot bar graph for top 5 classes
    plt.subplot(2, 1, 2)
    plt.barh(range(5), probabilities, align='center')
    plt.yticks(range(5), class_names)
    plt.gca().invert_yaxis()  # Invert y-axis to show highest probability at the top
    plt.xlabel('Probability')
    plt.title('Top 5 Predictions')
    plt.show()

# Call plot_solution function with the image path and the trained model
plot_solution(image_path1, model)

"""## Reminder for Workspace users
If your network becomes very large when saved as a checkpoint, there might be issues with saving backups in your workspace. You should reduce the size of your hidden layers and train again.
    
We strongly encourage you to delete these large interim files and directories before navigating to another page or closing the browser tab.
"""





